apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wq3tg42lw-go 
  janus-idp.io/tekton: wq3tg42lw-go
  backstage.io/kubernetes-id: wq3tg42lw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wq3tg42lw-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  