apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wq3tg42lw-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wq3tg42lw-go 
  name: wq3tg42lw-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wq3tg42lw-go 
